apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-api-deploy
  labels:
    app: nodejs-api-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-api-example
  template:
    metadata:
      labels:
        app: nodejs-api-example
    spec:
      containers:
      - name: nodejs-api
        image: 499092/luisgamarra:node-app
        imagePullPolicy: IfNotPresent
        #ports:
         # - containerPort: 3000
        env:
        - name: PORT
          value: "3005"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
  labels:
    app: nodejs-api-example
spec:
  type: NodePort
  selector:
    app: nodejs-api-example
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3005
